### PR TITLE
fix(azure): prevent duplicate pulumi role assignment URNs

### LINKED ISSUE #736: Policy conflicts in Azure
### Issue
Duplicate error with role assignment names in azure pulumi. For example, two buckets with same permissions in service breaks it.

I checked pulumi, but we should check tf as well.

### Expected

Should dedupe / merge them.

### PR DESCRIPTION
**Pull request by davemooreuws**
fixes #736 

Includes removal of unnecessary built in roles

[nitric-spec.json](https://github.com/user-attachments/files/19002553/nitric-spec.json)

### CODE REVIEW

**Review by HomelessDinosaur — APPROVED** [review]

File: cloud/azure/deploy/policy.go [hunk 1]
```diff
@@ -165,7 +168,13 @@ func (p *NitricAzurePulumiProvider) Policy(ctx *pulumi.Context, parent pulumi.Re
...
 				}
 
-				_, err = authorization.NewRoleAssignment(ctx, fmt.Sprintf("%s-%s", principal.Id.Name, roleName), &authorization.RoleAssignmentArgs{
+				roleAssignmentKey := fmt.Sprintf("%s-%s", principal.Id.Name, roleName)
+				if assignedRoles[roleAssignmentKey] {
+					// Skip if we have already assigned this role
+					continue
+				}
+
+				_, err = authorization.NewRoleAssignment(ctx, roleAssignmentKey, &authorization.RoleAssignmentArgs{
```
Comment (tjholm) [inline cloud/azure/deploy/policy.go:177]: role assignment key must also consider the resource being assigned in scope

File: cloud/azure/deploy/policy.go [hunk 2]
```diff
@@ -144,6 +144,9 @@ func (p *NitricAzurePulumiProvider) scopeFromResource(resource *deploymentspb.Re
 func (p *NitricAzurePulumiProvider) Policy(ctx *pulumi.Context, parent pulumi.Resource, name string, policy *deploymentspb.Policy) error {
 	opts := []pulumi.ResourceOption{pulumi.Parent(parent)}
 
+	// used to ensure we don't assign the same role multiple times
+	assignedRoles := make(map[string]bool)
+
```
Comment (tjholm) [inline cloud/azure/deploy/policy.go:149]: should be able to remove this with unique pulumi resource naming (including target resource).

**Review by tjholm — APPROVED** [review]
